version: '2'
services:
  fpm:
    build: PHP7fpm
    volumes:
      - ./app:/var/www/html

    ports:
      - "9000:9000"
    # links:
    #   - mysql

  nginx:
    build: Nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "8080:80"
      - "443:443"
    links:
      - fpm
      
  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=minhaapi